spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBYAwo5YvCulWrqTm+wIim7lCg1dc7eOVHKnGQh1K9iOL9OTLv7S3z9UeA34VooWxckz8Sami4gJNMzsueIR1D+LWOaFBlzcCc8k0MmCJ8qGlVw5BLWRPzv29h9Nhq3oe1h1Rjqhx1uAd06YOi5gE3U2cqhY/MJLTb2OH4IZFCHNNd5epUT+BQVvQlwj4Ujm7m6g/ApAmce77wY1hREVMbPiq35uWcLgBniMR6APUjCcjbmZ7pVvwQiG/NpeAKT3HGwRdA8VR4Y5HG2Np4t5WtS0E1Bfuy4pKa6LWRoB0J3NIgVfyEbVH+3WbW11g7LZ/Z7AfzQugcaMeqgx2EHtrU57esUw49LNcM3kToekojKvoo7ePbfzjYlXFlAUjhtpHg='

token:
  expiration_time: 864000000 
  secret: '{cipher}abee453d9f5b78eea46f78eba3bd3b94a8c619401e14595b123d45c4ae91fe45'

gateway:
  ip: 172.18.0.5

order_service:
  url:  http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.
